####################
############ SOURCE: https://github.com/dockersamples/example-voting-app
####################
version: "3"

services:
  vote:
    image: tommyleehamilton/vote:1.0
    command: python app.py
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier

  result:
    image: tommyleehamilton/result:1.0
    command: nodemon server.js
    ports:
      - "5001:80"
      - "5858:5858"
    networks:
      - front-tier
      - back-tier

  worker:
    image: tommyleehamilton/worker:1.0
    depends_on:
      - "redis"
    networks:
      - back-tier

  redis:
    image: redis:alpine
    ports: ["6379"]
    networks:
      - back-tier

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    networks:
      - back-tier
      
 
 
networks:
  front-tier:
  back-tier: